spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://fuseable-mysql.ccokzxghzzps.ap-northeast-2.rds.amazonaws.com:3306/fuseable?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: fuseable_2023
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:tcp://localhost/~/fuseable
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    spring:
      security:
        oauth2:
          client:
            registration:
              google:
                client-id: 192368607699-eon5h3ukefophnirb7brql8f4jr3cu6j.apps.googleusercontent.com
                client-secret: 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
                redirect-uri: http://localhost:8080/login/oauth2/code
                token-uri: https://oauth2.googleapis.com/token
                resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
                scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile



            provider:
              kakao:
                authorization_uri: https://kauth.kakao.com/oauth/authorize
                token_uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user_name_attribute: id

    custom:
      oauth2:
        kakao:
          client-id: kakao-client-id



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

#  jackson:
#    serialization:
#      fail-on-empty-beans: false

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace


AES:
  key: 0123456789012345

server:
  tomcat:
    max-http-post-size: 10MB





